import type { Metadata } from "next";
import "./globals.css";
import { TILE_ASSET_PATHS } from "./tileAssets";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {TILE_ASSET_PATHS.map((href) => (
          <link key={href} rel="preload" as="image" href={href} fetchPriority="high" />
        ))}
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
